name: Testing
on: push

jobs: 
  test_project:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/chechout@v2
    - name: Run Django unit tests
      run:
        pip3 install --user django
        python3 manage.py test